title: <p align="center"> Aman Lonare </p>

logo: "/images/logo.png?raw=true"

description:
  <p align="center">
  <a href="pdf/Resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/aman-lonare-546229103/">LinkedIn</a> |
  <a href="https://github.com/amanlonare">GitHub</a> |
  <a href="https://medium.com/@amanlonare">Medium</a>
  </p>
  
  <p align="justify">
  I graduated from IIT Bombay in 2020. Passionate about solving complex problems through data-driven solutions
  <br><br>
  I am working as a AI Research Engineer in Archetype Digital US. I worked as a Researcher in Hitachi Central Research Laboratory Tokyo.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
